version: "3.5"
services:
    java11:
        image: dheerajdac/ubuntu:java-11
        container_name: code
        command: sleep 60000
        volumes:
            - "~/.ssh/:/root/.ssh"
            - "~/.gitconfig:/root/.gitconfig"
            - "~/.m2/:/root/.m2/"
            - type: bind
              source: ./
              target: /workspace


